package graphicUI;

import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;

import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.LayoutStyle.ComponentPlacement;

import org.json.JSONException;
import org.json.JSONObject;

import communication.Communicator;

import elements.Request;

/**
 *
 * @author szedjani
 */
public class StudentReqDetailUI extends javax.swing.JFrame
{

	private Request selectedRequest;
	/**
	 * Creates new form StudentProfile
	 */
	private int buttonstate;

	public StudentReqDetailUI(Request selectedRequest, String userID)
	{
		buttonstate = -1;
		initComponents(selectedRequest, userID);
		setVisible(true);
		// setBounds(100, 100, 468, 307);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents(Request selectedRequest, String userID)
	{

		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextArea3 = new javax.swing.JTextArea();
		jLabel7 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jTextField5 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

		jTextField3.setEditable(false);
		jTextField3.setText(selectedRequest.getStartDate());
		jTextField3.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				jTextField3ActionPerformed(evt);
			}
		});

		jTextField4.setEditable(false);
		jTextField4.setText(selectedRequest.getEndDate());
		jTextField4.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				jTextField4ActionPerformed(evt);
			}
		});

		jScrollPane2
				.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

		jTextArea2.setEditable(false);
		jTextArea2.setColumns(20);
		jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
		jTextArea2.setLineWrap(true);
		jTextArea2.setRows(5);
		jTextArea2
				.setText("- Java\n- Apache Server\n- Oracle SQL\n- OOP Design Patterns");
		jTextArea2.setWrapStyleWord(true);
		jTextArea2.setMaximumSize(new java.awt.Dimension(384, 2147483647));
		jScrollPane2.setViewportView(jTextArea2);

		jScrollPane3
				.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

		jTextArea3.setEditable(false);
		jTextArea3.setColumns(20);
		jTextArea3.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
		jTextArea3.setLineWrap(true);
		jTextArea3.setRows(5);
		jTextArea3
				.setText("- team spirit\n- quick learning\n- driving licence");
		jTextArea3.setWrapStyleWord(true);
		jTextArea3.setMaximumSize(new java.awt.Dimension(384, 2147483647));
		jScrollPane3.setViewportView(jTextArea3);

		jLabel7.setText("Technical skills:");

		jLabel4.setText("Enddate:");

		jLabel11.setText("Non-technical skills:");

		jLabel5.setText("Payment:");

		jTextField5.setEditable(false);
		jTextField5.setText(selectedRequest.getPayment());
		jTextField5.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				jTextField5ActionPerformed(evt);
			}
		});

		jLabel2.setText("Position:");

		jTextField2.setEditable(false);
		jTextField2.setText(selectedRequest.getTitle());
		jTextField2.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				jTextField2ActionPerformed(evt);
			}
		});

		jLabel3.setText("Startdate:");

		/* Send response */
		lblResponse = new JLabel("Response:");
		lblResponse.setFont(new Font("����", Font.BOLD, 14));

		rdbtnYes = new JRadioButton("Yes");
		rdbtnYes.addMouseListener(new MouseAdapter()
		{
			@Override
			public void mouseClicked(MouseEvent arg0)
			{
				rdbtnNewRadioButtonMouseClicked(arg0);
			}
		});
		buttonGroup.add(rdbtnYes);
		rdbtnYes.setFont(new Font("����", Font.BOLD, 14));

		rdbtnNo = new JRadioButton("No");
		rdbtnNo.addMouseListener(new MouseAdapter()
		{
			@Override
			public void mouseClicked(MouseEvent arg0)
			{
				rdbtnNewRadioButton_1MouseClicked(arg0);
			}
		});
		buttonGroup.add(rdbtnNo);
		rdbtnNo.setFont(new Font("����", Font.BOLD, 14));

		JButton btnSendResponse = new JButton("Send response");
		btnSendResponse.addMouseListener(new MouseAdapter()
		{
			@Override
			public void mouseClicked(MouseEvent e)
			{
				JSONObject message = new JSONObject();
				try
				{
					message.put("MessageType", "answer");
					message.put("ID", userID);
					message.put("RequestID", selectedRequest.getId());
					switch (buttonstate)
					{
					case 0:
						message.put("Answer", Request.State.NO.name());
						Communicator.sendMessage(message);
						JOptionPane.showMessageDialog(new JFrame(),
								"The response have sent!");
						break;
					case 1:
						message.put("Answer", Request.State.YES.name());
						Communicator.sendMessage(message);
						JOptionPane.showMessageDialog(new JFrame(),
								"The response have sent!");
						break;
					default:
						JOptionPane.showMessageDialog(new JFrame(),
								"The response have sent!");
						break;
					}
				}
				catch (JSONException | IOException e1)
				{
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}

			}
		});

		// ////////////////////////////////////////////////////////////

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(layout
				.createParallelGroup(Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel2)
																.addGap(18)
																.addComponent(
																		jTextField2,
																		GroupLayout.PREFERRED_SIZE,
																		GroupLayout.DEFAULT_SIZE,
																		GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel3)
																.addPreferredGap(
																		ComponentPlacement.UNRELATED)
																.addComponent(
																		jTextField3,
																		GroupLayout.PREFERRED_SIZE,
																		96,
																		GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		ComponentPlacement.UNRELATED)
																.addComponent(
																		jLabel4)
																.addPreferredGap(
																		ComponentPlacement.UNRELATED)
																.addComponent(
																		jTextField4,
																		GroupLayout.PREFERRED_SIZE,
																		85,
																		GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel5)
																.addPreferredGap(
																		ComponentPlacement.UNRELATED)
																.addComponent(
																		jTextField5,
																		GroupLayout.PREFERRED_SIZE,
																		96,
																		GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.LEADING)
																				.addComponent(
																						jScrollPane2,
																						GroupLayout.PREFERRED_SIZE,
																						196,
																						GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel7))
																.addPreferredGap(
																		ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.LEADING)
																				.addComponent(
																						jScrollPane3,
																						GroupLayout.PREFERRED_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel11)))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		lblResponse)
																.addPreferredGap(
																		ComponentPlacement.UNRELATED)
																.addComponent(
																		rdbtnYes)
																.addGap(27)
																.addComponent(
																		rdbtnNo)
																.addPreferredGap(
																		ComponentPlacement.RELATED,
																		63,
																		Short.MAX_VALUE)
																.addComponent(
																		btnSendResponse)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														jTextField2,
														GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE,
														GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														jTextField3,
														GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE,
														GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel4)
												.addComponent(
														jTextField4,
														GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE,
														GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												Alignment.BASELINE)
												.addComponent(jLabel5)
												.addComponent(
														jTextField5,
														GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE,
														GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												Alignment.BASELINE)
												.addComponent(jLabel7)
												.addComponent(jLabel11))
								.addPreferredGap(ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												Alignment.LEADING)
												.addComponent(
														jScrollPane2,
														GroupLayout.PREFERRED_SIZE,
														68,
														GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jScrollPane3,
														GroupLayout.PREFERRED_SIZE,
														68,
														GroupLayout.PREFERRED_SIZE))
								.addGap(18)
								.addGroup(
										layout.createParallelGroup(
												Alignment.BASELINE)
												.addComponent(lblResponse)
												.addComponent(rdbtnYes)
												.addComponent(rdbtnNo)
												.addComponent(
														btnSendResponse,
														GroupLayout.PREFERRED_SIZE,
														25,
														GroupLayout.PREFERRED_SIZE))
								.addContainerGap(18, Short.MAX_VALUE)));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jTextField3ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField3ActionPerformed

	private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jTextField4ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField4ActionPerformed

	private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jTextField5ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField5ActionPerformed

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jTextField2ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField2ActionPerformed

	/* sending response */
	protected void rdbtnNewRadioButton_1MouseClicked(MouseEvent arg0)
	{
		setButtonstate(0);
	}

	protected void rdbtnNewRadioButtonMouseClicked(MouseEvent arg0)
	{
		setButtonstate(1);
	}

	public int getButtonstate()
	{
		return buttonstate;
	}

	public void setButtonstate(int buttonstate)
	{
		this.buttonstate = buttonstate;
	}

	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextArea jTextArea3;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private JLabel lblResponse;
	private JRadioButton rdbtnYes;
	private JRadioButton rdbtnNo;
	private final ButtonGroup buttonGroup = new ButtonGroup();
}
