package graphicUI;

import skills.NonTechSkills;
import skills.TechSkills;
import elements.Student;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author szedjani
 */
public class StudentDataUI extends javax.swing.JFrame {

    Student student;

    /**
     * Creates new form StudentProfile
     */
    public StudentDataUI(Student student) {
	this.student = student;
	initComponents();
	setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	jTextField3 = new javax.swing.JTextField();
	jTextField4 = new javax.swing.JTextField();
	jScrollPane2 = new javax.swing.JScrollPane();
	jTextArea2 = new javax.swing.JTextArea();
	jScrollPane3 = new javax.swing.JScrollPane();
	jTextArea3 = new javax.swing.JTextArea();
	jLabel7 = new javax.swing.JLabel();
	jLabel4 = new javax.swing.JLabel();
	jLabel11 = new javax.swing.JLabel();
	jLabel5 = new javax.swing.JLabel();
	jTextField5 = new javax.swing.JTextField();
	jLabel6 = new javax.swing.JLabel();
	jLabel1 = new javax.swing.JLabel();
	jTextField6 = new javax.swing.JTextField();
	jTextField1 = new javax.swing.JTextField();
	jLabel2 = new javax.swing.JLabel();
	jTextField2 = new javax.swing.JTextField();
	jLabel3 = new javax.swing.JLabel();

	setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
	setResizable(false);

	jTextField3.setEditable(false);
	jTextField3.setText(Integer.toString(student.getAge()));
	jTextField3.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		jTextField3ActionPerformed(evt);
	    }
	});

	jTextField4.setEditable(false);
	jTextField4.setText(student.getSex());
	jTextField4.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		jTextField4ActionPerformed(evt);
	    }
	});

	jScrollPane2
		.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

	jTextArea2.setEditable(false);
	jTextArea2.setColumns(20);
	jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
	jTextArea2.setLineWrap(true);
	jTextArea2.setRows(5);

	String techSkillsString = new String();
	for (TechSkills skill : student.getTechSkills())
	    techSkillsString += "- " + skill.name() + '\n';

	jTextArea2.setText(techSkillsString);
	jTextArea2.setWrapStyleWord(true);
	jTextArea2.setMaximumSize(new java.awt.Dimension(384, 2147483647));
	jScrollPane2.setViewportView(jTextArea2);

	jScrollPane3
		.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

	jTextArea3.setEditable(false);
	jTextArea3.setColumns(20);
	jTextArea3.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
	jTextArea3.setLineWrap(true);
	jTextArea3.setRows(5);

	String nonTechSkillsString = new String();
	for (NonTechSkills skill : student.getNonTechSkills())
	    nonTechSkillsString += "- " + skill.name() + '\n';

	jTextArea3.setText(nonTechSkillsString);
	jTextArea3.setWrapStyleWord(true);
	jTextArea3.setMaximumSize(new java.awt.Dimension(384, 2147483647));
	jScrollPane3.setViewportView(jTextArea3);

	jLabel7.setText("Technical skills:");

	jLabel4.setText("Sex:");

	jLabel11.setText("Non-technical skills:");

	jLabel5.setText("GPA:");

	jTextField5.setEditable(false);
	jTextField5.setText(Float.toString(student.getGpa()));
	jTextField5.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		jTextField5ActionPerformed(evt);
	    }
	});

	jLabel6.setText("Phone number:");

	jLabel1.setText("Name of student:");

	jTextField6.setEditable(false);
	jTextField6.setText(student.getContactNumber());
	jTextField6.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		jTextField6ActionPerformed(evt);
	    }
	});

	jTextField1.setEditable(false);
	jTextField1.setText(student.getStudentName());
	jTextField1.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		jTextField1ActionPerformed(evt);
	    }
	});

	jLabel2.setText("Grade:");

	jTextField2.setEditable(false);
	jTextField2.setText(Integer.toString(student.getGrade()));
	jTextField2.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		jTextField2ActionPerformed(evt);
	    }
	});

	jLabel3.setText("Age:");

	javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
		getContentPane());
	getContentPane().setLayout(layout);
	layout.setHorizontalGroup(layout
		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGroup(
			layout.createSequentialGroup()
				.addContainerGap()
				.addGroup(
					layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
							layout.createSequentialGroup()
								.addComponent(
									jLabel1)
								.addPreferredGap(
									javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(
									jTextField1))
						.addGroup(
							layout.createSequentialGroup()
								.addGroup(
									layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(
											jLabel2)
										.addComponent(
											jLabel3)
										.addComponent(
											jLabel5))
								.addGap(70, 70,
									70)
								.addGroup(
									layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(
											jTextField2)
										.addGroup(
											layout.createSequentialGroup()
												.addGroup(
													layout.createParallelGroup(
														javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
															javax.swing.GroupLayout.Alignment.TRAILING,
															layout.createSequentialGroup()
																.addComponent(
																	jTextField5,
																	javax.swing.GroupLayout.PREFERRED_SIZE,
																	96,
																	javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																	javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																	jLabel6)
																.addGap(18,
																	18,
																	18))
														.addGroup(
															layout.createSequentialGroup()
																.addComponent(
																	jTextField3,
																	javax.swing.GroupLayout.PREFERRED_SIZE,
																	96,
																	javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																	javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																	jLabel4)
																.addGap(69,
																	69,
																	69)))
												.addGroup(
													layout.createParallelGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														false)
														.addComponent(
															jTextField4)
														.addComponent(
															jTextField6,
															javax.swing.GroupLayout.PREFERRED_SIZE,
															98,
															javax.swing.GroupLayout.PREFERRED_SIZE)))))
						.addGroup(
							javax.swing.GroupLayout.Alignment.TRAILING,
							layout.createSequentialGroup()
								.addGroup(
									layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(
											jScrollPane2,
											javax.swing.GroupLayout.PREFERRED_SIZE,
											196,
											javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(
											jLabel7))
								.addPreferredGap(
									javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
									layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(
											jScrollPane3)
										.addGroup(
											layout.createSequentialGroup()
												.addComponent(
													jLabel11)
												.addGap(0,
													0,
													Short.MAX_VALUE)))))
				.addGap(7, 7, 7)));
	layout.setVerticalGroup(layout
		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGroup(
			layout.createSequentialGroup()
				.addContainerGap()
				.addGroup(
					layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jLabel1)
						.addComponent(
							jTextField1,
							javax.swing.GroupLayout.PREFERRED_SIZE,
							javax.swing.GroupLayout.DEFAULT_SIZE,
							javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(
					javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(
					layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jLabel2)
						.addComponent(
							jTextField2,
							javax.swing.GroupLayout.PREFERRED_SIZE,
							javax.swing.GroupLayout.DEFAULT_SIZE,
							javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(
					javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(
					layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jLabel3)
						.addComponent(
							jTextField3,
							javax.swing.GroupLayout.PREFERRED_SIZE,
							javax.swing.GroupLayout.DEFAULT_SIZE,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel4)
						.addComponent(
							jTextField4,
							javax.swing.GroupLayout.PREFERRED_SIZE,
							javax.swing.GroupLayout.DEFAULT_SIZE,
							javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(
					javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(
					layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jLabel5)
						.addComponent(
							jTextField5,
							javax.swing.GroupLayout.PREFERRED_SIZE,
							javax.swing.GroupLayout.DEFAULT_SIZE,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel6)
						.addComponent(
							jTextField6,
							javax.swing.GroupLayout.PREFERRED_SIZE,
							javax.swing.GroupLayout.DEFAULT_SIZE,
							javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(
					javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(
					layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jLabel7)
						.addComponent(jLabel11))
				.addPreferredGap(
					javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(
					layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(
							jScrollPane2,
							javax.swing.GroupLayout.PREFERRED_SIZE,
							68,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(
							jScrollPane3,
							javax.swing.GroupLayout.PREFERRED_SIZE,
							68,
							javax.swing.GroupLayout.PREFERRED_SIZE))
				.addContainerGap(
					javax.swing.GroupLayout.DEFAULT_SIZE,
					Short.MAX_VALUE)));

	pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField3ActionPerformed
									     // TODO
									     // add
									     // your
									     // handling
									     // code
									     // here:
    }// GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField4ActionPerformed
									     // TODO
									     // add
									     // your
									     // handling
									     // code
									     // here:
    }// GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField5ActionPerformed
									     // TODO
									     // add
									     // your
									     // handling
									     // code
									     // here:
    }// GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField6ActionPerformed
									     // TODO
									     // add
									     // your
									     // handling
									     // code
									     // here:
    }// GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
									     // TODO
									     // add
									     // your
									     // handling
									     // code
									     // here:
    }// GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField2ActionPerformed
									     // TODO
									     // add
									     // your
									     // handling
									     // code
									     // here:
    }// GEN-LAST:event_jTextField2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
